### ISSUE TITLE
Support subtitle that have cues with zero length

### ISSUE THREAD

**Issue by SergioEstevao** [dagronf/SwiftSubtitles#11]
I've come across of some subtitles that that cue entries where the start time is equal to the end time.

This will cause a the decoder to throw an exception saying that the start time is less than the end time.

This code is a assert on the `Subtitles.Cue-> init method`.

Can we change the asset to be

`assert(startTime <= endTime)`

**Comment by dagronf** [comment]
Hey mate - can you share a subtitle file with the issue? Would be good to have something real to write some tests against.

what format are you trying to import?

**Comment by SergioEstevao** [comment]
I'm trying to import this file: `https://s3.fr-par.scw.cloud/s3.castopod.cloud/c89b2cfc0e4c784122216b2ad9d5d54b7/podcasts/podcast/26-transcript.srt`

It's in the Subrip format

**Comment by dagronf** [comment]
Hi @SergioEstevao can you please check out 1.6.0 and see if this fixes your issue?

**Comment by SergioEstevao** [comment]
Working great! thanks @dagronf !
