### ISSUE TITLE
vtt parse seems not correctly for some file

### ISSUE THREAD

**Issue by Josscii** [dagronf/SwiftSubtitles#14]
Since this file doesn’t seem to be standard, there are some issues with the parsed subtitles. It could be that there’s an issue with the current parsing implementation, or perhaps more fault tolerance is needed.

I tried importing the file into the iOS Files app, and it parsed and worked correctly in the preview. Here’s a screenshot.

https://github.com/user-attachments/assets/021ed628-5761-4bb9-b90e-0372d4787604

```
and<00:00:18.400><c> we'll</c><00:00:18.560><c> go</c><00:00:18.720><c> to</c><00:00:18.880><c> the</c><00:00:18.960><c> web</c><00:00:19.119><c> page</c><00:00:19.359><c> in</c><00:00:19.520><c> a</c><00:00:19.600><c> minute</c>
```
These seems should be ignored.

_Originally posted by @Josscii in https://github.com/dagronf/SwiftSubtitles/issues/13#issuecomment-2554330014_

**Comment by dagronf** [comment]
Strangely enough - this file is a valid VTT file.  I've gone through the spec and it seems like there's nothing untoward in the file.

> `and<00:00:18.400><c> we'll</c><00:00:18.560><c> go</c><00:00:18.720><c> to</c><00:00:18.880><c> the</c><00:00:18.960><c> web</c><00:00:19.119><c> page</c><00:00:19.359><c> in</c><00:00:19.520><c> a</c><00:00:19.600><c> minute</c>`

VTT supports embedding timestamps _within_ a cue, to identify when individual words are spoken within the cue itself. 

```
00:00:28.560 --> 00:00:30.790 align:start position:0%
keith johnson
peter<00:00:28.880><c> ladoffo</c><00:00:28.880><c> lattifogue</c><00:00:30.160><c> was</c><00:00:30.400><c> certainly</c>

00:00:30.790 --> 00:00:30.800 align:start position:0%
peter ladoffo lattifogue was certainly
```

You can see that the embedded timestamps fit within the time range (it's an error if the embedded timestamps are outside the cue's time range

This library does NOT support word timestamps, so the cue will pass into the `Subtitle.Cue` directly with no further parsing.

The reason that it 'works' within the files app is that the subtitles are changing quickly between these cues (which are mostly identical in the textual content) so you aren't noticing that the cue has changed, giving the appearance that it's choosing a cue (somehow).

For example :-

```
00:00:23.840 --> 00:00:24.710 align:start position:0%
have it yet it's called a course in
phonetics

00:00:24.710 --> 00:00:24.720 align:start position:0%
phonetics
```

The second 'phonetics' will appear onscreen for approximately 10ms, which would mostly be imperceptible.

So, as a result, it is up to the user of the library to determine what they want to do with the content. They can choose to ignore a cue that contains an embedded time.

So, I think the library shouldn't change as it depends entirely what the client requires.

**Comment by Josscii** [comment]
Thanks for your reply. Does it mean, with these parsed timestamp cues, the
client should try parse and decide how to do with it?

Darren Ford ***@***.***>于2024年12月21日 周六13:22写道：

**Comment by dagronf** [comment]
At this point, yes you'll need to handle these yourself.  SwiftSubtitles currently only parses down to the cue level, not the word level.

**Comment by Josscii** [comment]
Yeah, you are right, I should do it myself, thanks for your patients and great work!
