### ISSUE TITLE
Feature Request: Add Subtitle Concatenation Functionality

### ISSUE THREAD

**Issue by zh00bc** [dagronf/SwiftSubtitles#7]
First off, thank you for your great work on this library. It has been very useful for handling subtitle files.

I would like to request a new feature that allows concatenating subtitle cues into a continuous sentence. This functionality would be beneficial for applications that need to display subtitles as a single, coherent text instead of individual cues.

Implementing this feature would enhance the library's capabilities and provide a convenient solution for developers working with subtitles.

**Comment by dagronf** [comment]
Hey @zh00bc, thanks for all the nice comments!

There is a method `text` on the `Subtitle` object that returns all of the cue text as an array of strings. You could then concatenate those strings into a single string, like :-

```swift
// This returns all the cue text as an array of strings (one for each cue)
let allCueText = subtitles.text

// Merge all of the strings into a single string
let allText = allCueText.reduce("") { partialResult, cueText in partialResult + cueText }
```

In the case of wanting a single sentence, you'd (additionally) need to remove any newlines within the cue text with a space

It shouldn't be overly difficult to strip any newlines within each cue text to remove it if you needed (eg. replace it with a whitespace), like

```swift
let allText = allCueText.reduce("") { partialResult, cueText in
   let cleaned = cueText.replacingOccurrences(of: "\n", with: " ")
   return partialResult + cleaned
}
```

Is this what you're looking for?

**Comment by zh00bc** [comment]
Hey @dagronf, sorry for the delayed response. Here's what I'm looking for:
```swift
let cue1 = subtitles.cues[x]
let cue2 = subtitles.cues[y]
let cue = cue1 + cue2
```

**Comment by zh00bc** [comment]
However, I think implementing it myself is also straightforward, so it doesn't matter whether this feature is added or not.

**Comment by dagronf** [comment]
@zh00bc In your example, is it only the text that gets added together when two cues are added?  What happens with the times/positions etc?

**Comment by zh00bc** [comment]
@dagronf When two cues are merged, the times, duration, and text etc should all be updated.

**Comment by dagronf** [comment]
@zh00bc Updated how?

If one cue has a time range of  1.000 -> 2.000 and the other has 3.400 -> 5.000, how should it be combined? A simple range merge?  So the resulting range is 1.000 -> 5.000?

**Comment by zh00bc** [comment]
@dagronf Merging the subtitles in such a way can potentially result in a mismatch between the subtitles and the visuals, and I overlooked this aspect.
