### ISSUE TITLE
Cues is not create

### ISSUE THREAD

**Issue by malierbas** [dagronf/SwiftSubtitles#8]
my srt text (String) in Turkish language;

1
0:00:00.000 --> 0:00:02.000
Merhaba arkadaşlar.
2
0:00:02.000 --> 0:00:04.000
Kanalıma hoş geldiniz.
3
0:00:04.000 --> 0:00:07.000
Bugün sizler için niyet ettim.
4
0:00:07.000 --> 0:00:10.000
Falk kapattım sizler de direğinizi tutup.
5
0:00:10.000 --> 0:00:12.000
Falınızı dinleyebilirsiniz.
6
0:00:12.000 --> 0:00:15.000
Ama öncelikle sizden rica'm.
7
0:00:15.000 --> 0:00:18.000
Kanalıma abone olup videolarımı beğenmeyi,
8
0:00:18.000 --> 0:00:22.000
yorum yapmayı ve bildirimlerini açmayı unutmayınız.
9
0:00:22.000 --> 0:00:24.000
Şimdiden teşekkür ediyorum.
10
0:00:24.000 --> 0:00:30.000
Ve felınıza geçiyorum.

decoding codes;
` 
 let coder = Subtitles.Coder.SRT()
 let subtitles = try? coder.decode(text)
`
When I try to print them, I get a nil value.

**Comment by dagronf** [comment]
Hey @malierbas,

I believe your srt file is incorrectly formatted. According to the [specs](https://en.wikipedia.org/wiki/SubRip), each cue should be separated by at least one blank line.

it should look like 

```
1
0:00:00.000 --> 0:00:02.000
Merhaba arkadaşlar.

2
0:00:02.000 --> 0:00:04.000
Kanalıma hoş geldiniz.

3
0:00:04.000 --> 0:00:07.000
Bugün sizler için niyet ettim.

4
0:00:07.000 --> 0:00:10.000
Falk kapattım sizler de direğinizi tutup.
```

what do you think?
